apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../deploy.development
resources:
  - ../../resource
components:
  - ../../component_a
  - ../../component_b

commonLabels:
  for: github
