apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

patchesJson6902:
  - path: ingress_patch.yml
    target:
      group: extensions
      version: v1beta1
      kind: Ingress
      name: cloud